### PR TITLE
feat: electron dev, prod, package integration

### PR DESCRIPTION
**Pull request by damnko**
Solves #14

Hi @JayKan please let me know what you think about this implementation. I had to change some import paths from absolute to relative because I was having issues during electron packaging.

### CODE REVIEW

**Comment by JayKan** [comment]
@damnko,

What was the reason you've switched from using relative path instead of absolute path on importing modules? For instance, I see you modified the `src/filers`..

I will look at deeper look at tomorrow and will merge your changes. Thanks a lot for putting this effort @damnko 👍

**Comment by damnko** [comment]
Yes I changed all the relative paths because I were getting errors like `module not found` the were solved that way. By the way that was happening while I was trying to build the electron app in another way (I don't remember the details), with `electron-packager` it works even with absolute paths. So if you'd like I'll revert the paths back to the absolute form they were before, just let me know and I'll update the PR.

**Comment by JayKan** [comment]
@damnko,

A million thanks for putting up your time and get this working. Don't worry about the `absolute path` issue. I have already merged your awesome code and did some refactoring to take care of this. A few minor things I've noticed and I have created PR for you #26, #27. Other than that, everything looks goood! Once again, thanks A LOT for your help 💯

**Comment by damnko** [comment]
Thanks I really appreciate your feedback! Looking forward to adding more features.

**Pull request merged**
